export const LOGIN_ROUTE = "/login"
// export const REGISTER_ROUTE = "/registration"
// export const AUTH_FAILURE_ROUTE = "/authentication_failure"
// export const USER_EXISTS_ROUTE = "/user_already_exists"
// export const CORRECT_TIME_ROUTE = "/ok_time"
// export const WRONG_TIME_ROUTE = "/wrong_time"
