CREATE TABLE ARTIST_INFO
(
    ID BIGSERIAL NOT NULL
        CONSTRAINT ARTIST_INFO_PKEY
            PRIMARY KEY,
    CABINET      BIGINT NOT NULL
        CONSTRAINT CABINET_UNIQUE
            UNIQUE,
    PROCEDURE_ID BIGINT
        CONSTRAINT PROCEDURE_ID_REFERENCES_PROCEDURE
            REFERENCES PROCEDURE
);

INSERT INTO ARTIST_INFO (cabinet, procedure_id)
VALUES (111, 1);
INSERT INTO ARTIST_INFO (cabinet, procedure_id)
VALUES (222, 2);
INSERT INTO ARTIST_INFO (cabinet, procedure_id)
VALUES (333, 3);

