version: "3.9"

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: "no"
    volumes:
      - ../src/main/resources/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 30s
      retries: 5
  jvm_app:
    build:
      context: ../
      dockerfile: ./env/jvm_app/DockerfileJvmApp
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      COVID_API_KEY: ${COVID_API_KEY}
      CORS_FRONT_HOST: ${CORS_FRONT_HOST}
    ports:
      - "8080:8080"
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:
      context: ../
      dockerfile: ./env/client/DockerfileClient
    environment:
      REACT_APP_SERVER_HOST: ${REACT_APP_SERVER_HOST}
    ports:
      - "3000:3000"
    restart: "no"
    depends_on:
      jvm_app:
        condition: service_healthy
